spring.application.name=fidness

# Puerto del servidor
server.port=80

# ==========================
# Base de Datos MySQL
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/fidness?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Atun2022.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# Firebase Storage
# ==========================
firebase.bucket.name=fidness-6cd65.firebasestorage.app
firebase.storage.path=fidness
firebase.json.path=firebase
firebase.json.file=fidness-6cd65-firebase-adminsdk-fbsvc-e8cc229292.json

# ==========================
# Hibernate
# ==========================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Thymeleaf
# ==========================
spring.thymeleaf.cache=false

# ==========================
# Multipart
# ==========================
spring.servlet.multipart.max-file-size=16MB
spring.servlet.multipart.max-request-size=16MB

# ==========================
# Correo Gmail
# ==========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=SU_USUARIO
spring.mail.password=SU_CONTRASEÑA

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================
# FIDNESS
# ==========================
fidness.servidor=http://localhost
fidness.clave.activacion=FIDNESS-G25-2026-Ariel

# Internacionalizacion
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false